title: "実践的 Oracle SQL 徹底演習（完全版）"
summary: |-
  「SQLを学びたいけど、DBの設定が面倒」「教科書のクエリを実務でどう使えばいいかわからない」という初級エンジニアから、「複雑なクエリを書くヒントが欲しい」という上級エンジニアまで、幅広い方を対象にしています。Oracleが提供する学習環境「Oracle FreeSQL」を使い、現場で使えるSQLの感覚を身につけるための問題集です。

  全問題数は262問(通常版の全収録問題146問に加え、上級者向けの問題を116問追加収録)。

  ※本書は「完全版」です。一般レベル向けの無料「通常版」もあわせてご用意しています。収録内容は下記リンクよりご確認いただけます。
  https://zenn.dev/kinopp/books/95dad9a1f9513b
topics:
  - "sql"
  - "データベース"
  - "rdb"
  - "oracle"
published: true
price: 700
toc_depth: 1
chapters:
  - "a671c0"
  - "7242b7"
  - "8ae3e1"
  - "d8a260"
  - "3f3a78"
  - "679c6e"
  - "3a688b"
  - "9efa63"
  - "b0084e"
  - "9d52a4"
  - "ecd3f0"
  - "bebedc"
  - "bb5535"
  - "199c3c"
  - "563922"
  - "d320c9"
  - "fce7af"
  - "ad2fff"
  - "93b0be"
  - "8136f1"
  - "63c12a"
  - "a907c4"
  - "1b1bce"
  - "4bf59b"
  - "448866"
  - "7cab3b"
  - "111a9a"
  - "31ded4"
  - "b9c108"
  - "e239d0"
  - "22f35c"
  - "3a0a4e"
  - "b21674"
  - "bac1cb"
  - "6cfba0"
  - "bcb623"
  - "c7c744"