title: "実践的OracleSQL徹底演習（完全版）"
summary: |-
  【⚠️注意】
  一般レベル向けに、無料の「通常版」を提供しています。
  「完全版」にどのような問題が収録されているかは下記リンクの「通常版」で参照できます。
  https://zenn.dev/kinopp/books/95dad9a1f9513b

  【説明】
  「SQLを学びたいけど、DBの設定が面倒…」「教科書のクエリは実務でどう使うの？」そんな悩みを抱えるすべての初級エンジニアから「複雑なクエリを書くにはどうすればよいのか、ヒントを得たい」という上級エンジニア。Oracleが提供する最新環境「Oracle FreeSQL」を使い倒し、現場で通用する「本物のSQL力」を叩き込むトレーニングを公開します！

  【バージョン】1.3.6　全100問突破！
topics:
  - "sql"
  - "データベース"
  - "oracle"
  - "oraclesql"
published: true
price: 700
toc_depth: 1
chapters:
  - "a671c0"
  - "7242b7"
  - "8ae3e1"
  - "d8a260"
  - "679c6e"
  - "9efa63"
  - "9d52a4"
  - "ecd3f0"
  - "bebedc"
  - "199c3c"
  - "563922"
  - "fce7af"
  - "ad2fff"
  - "93b0be"
  - "63c12a"
  - "1b1bce"
  - "4bf59b"
  - "7cab3b"
  - "111a9a"
  - "e239d0"
  - "3a0a4e"
  - "bcb623"
  - "c7c744"