title: "実践的OracleSQL徹底演習（通常版）"
summary: |-
  【⚠️注意】
  上級レベル向けに、有料の「完全版」を提供しています。
  https://zenn.dev/kinopp/books/0b24d659785f31

  【説明】
  SQLを学びたいけど、DBの設定が面倒…」「教科書のクエリは実務でどう使うの？」そんな悩みを抱えるすべての初級エンジニアから「複雑なクエリを書くにはどうすればよいのか、ヒントを得たい」という上級エンジニア。Oracleが提供する最新環境「Oracle FreeSQL」を使い倒し、現場で通用する「本物のSQL力」を叩き込むトレーニングを公開します！
topics:
  - "sql"
  - "データベース"
  - "oracle"
  - "oraclesql"
published: true
price: 0
toc_depth: 1
chapters:
  - "78341e"
  - "8dea94"
  - "b4495d"
  - "e44afa"
  - "9ed232"
  - "c3959c"
  - "fea226"
  - "bd0277"
  - "8255e4"
  - "e36447"
  - "120643"
  - "468174"
  - "3781e5"
  - "deabbf"
  - "6983d6"
  - "21e407"
  - "cadba8"
  - "1eb30e"
  - "2d2701"
  - "1b4f2d"
  - "a10e46"