title: "実践的 Oracle SQL 徹底演習（通常版）"
summary: |-
  「SQLを学びたいけど、DBの設定が面倒」「教科書のクエリを実務でどう使えばいいかわからない」という初級エンジニアから、「複雑なクエリを書くヒントが欲しい」という上級エンジニアまで、幅広い方を対象にしています。Oracleが提供する学習環境「Oracle FreeSQL」を使い、現場で使えるSQLの感覚を身につけるための問題集です。

  全問題数は146問（問題のみ116問）。

  ※本書は無料の「通常版」です。上級レベル向けの問題を追加収録した有料の「完全版」もご用意しています。→ 完全版の問題（解答・解説なし）は通常版でも収録してます。
  https://zenn.dev/kinopp/books/0b24d659785f31
topics:
  - "sql"
  - "データベース"
  - "rdb"
  - "oracle"
published: true
price: 0
toc_depth: 1
chapters:
  - "78341e"
  - "8dea94"
  - "b4495d"
  - "e44afa"
  - "53c3a1"
  - "9ed232"
  - "52ccc3"
  - "c3959c"
  - "f8eace"
  - "fea226"
  - "bd0277"
  - "8255e4"
  - "4e7062"
  - "e36447"
  - "120643"
  - "7cdb99"
  - "468174"
  - "3781e5"
  - "deabbf"
  - "9f411d"
  - "6983d6"
  - "798215"
  - "21e407"
  - "cadba8"
  - "97c5e7"
  - "2d2701"
  - "1b4f2d"
  - "6b0561"
  - "aa990c"
  - "a10e46"
  - "850a5f"
  - "1eb30e"
  - "48f7c2"
  - "e65688"
  - "c6e605"